# Generated by Django 4.1.5 on 2023-01-19 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdVotes', models.CharField(blank=True, max_length=5000, verbose_name='Созданные голосования')),
                ('createdReports', models.CharField(blank=True, max_length=5000, verbose_name='Созданные жалобы')),
                ('usedVotes', models.CharField(blank=True, max_length=5000, verbose_name='Участие в голосованиях')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
