# Generated by Django 4.1.5 on 2023-01-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='createdVotes',
            field=models.CharField(blank=True, default='none', max_length=5000, verbose_name='Созданные голосования'),
        ),
    ]
