# Generated by Django 4.1.5 on 2023-01-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_options_alter_profile_createdvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='createdReports',
            field=models.CharField(blank=True, default='none', max_length=5000, verbose_name='Созданные жалобы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usedVotes',
            field=models.CharField(blank=True, default='none', max_length=5000, verbose_name='Участие в голосованиях'),
        ),
    ]
