# Generated by Django 4.1.5 on 2023-01-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_votes_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOfVote', models.CharField(max_length=250, verbose_name='ID голосования')),
                ('textOfRepot', models.TextField(verbose_name='Текст жалобы')),
                ('status', models.CharField(max_length=250, verbose_name='Статус жалобы')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
