# Generated by Django 4.1.5 on 2023-01-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='status',
            field=models.CharField(blank=True, default='0: Wait for verification', max_length=250, verbose_name='Статус жалобы'),
        ),
    ]
