# Generated by Django 4.1.5 on 2023-01-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_reports_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='textOfRepot',
            new_name='textOfReport',
        ),
        migrations.AlterField(
            model_name='reports',
            name='idOfVote',
            field=models.CharField(blank=True, max_length=250, verbose_name='ID голосования'),
        ),
    ]
